import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import Link from "next/link";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function AdminActivityPage({ searchParams }: { searchParams: Promise<{ action?: string; from?: string; to?: string }> }) {
  const session = await getServerSession(authOptions);
  if ((session?.user as { role?: string } | undefined)?.role !== "ADMIN") redirect("/");
  const { action, from, to } = await searchParams;
  const logs = await prisma.adminAuditLog.findMany({ where: { ...(action ? { action: { contains: action, mode: "insensitive" } } : {}), ...(from || to ? { createdAt: { ...(from ? { gte: new Date(`${from}T00:00:00.000Z`) } : {}), ...(to ? { lte: new Date(`${to}T23:59:59.999Z`) } : {}) } } : {}) }, orderBy: { createdAt: "desc" }, take: 100, include: { admin: { select: { name: true, email: true } } } });
  return <div><div className="mb-8"><p className="text-[10px] uppercase tracking-[0.18em] text-soft-400">Admin / accountability</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-soft-700">Activity.</h1><p className="mt-2 text-sm text-soft-500">A record of changes made across the studio.</p></div><form className="mb-6 grid gap-3 sm:grid-cols-[1fr_auto_auto_auto]"><input name="action" defaultValue={action} placeholder="Filter action, e.g. product.update" className="input-soft py-2.5" /><input name="from" type="date" defaultValue={from} className="input-soft py-2.5" /><input name="to" type="date" defaultValue={to} className="input-soft py-2.5" /><button className="btn-secondary py-2.5">Filter</button></form><div className="overflow-x-auto border-y border-soft-200/70"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-soft-200/70 text-xs uppercase tracking-wider text-soft-400"><tr><th className="py-4">Action</th><th>Admin</th><th>Target</th><th>Time</th></tr></thead><tbody className="divide-y divide-soft-200/60">{logs.map((log) => <tr key={log.id}><td className="py-4 font-medium text-soft-700">{log.action}</td><td className="text-soft-500">{log.admin.name ?? log.admin.email}</td><td className="text-soft-500">{log.targetType}{log.targetId ? ` · ${log.targetId.slice(0, 8)}` : ""}</td><td className="text-soft-400">{new Date(log.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>{logs.length === 0 && <div className="glass mt-4 rounded-2xl p-10 text-center text-sm text-soft-500">No activity matches these filters.</div>}<Link href="/admin/activity" className="mt-5 inline-block text-xs text-soft-500 underline underline-offset-4">Clear filters</Link></div>;
}